version: '3.1'
services:
  myblog-frontend:
    restart: always
    image: nginx
    container_name: myblog-frontend
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot/dist:/usr/share/nginx/wwwroot

