version: '3.1'
services:
  myblog-admin:
    build: .
    container_name: myblog-admin
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime # 设置时区和宿主机一致

networks:
  default:
    external:
      name: myblog
