server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://119.3.222.119:8000/oauth/token
      user-authorization-uri: http://119.3.222.119:8000/oauth/authorize
    resource:
      token-info-uri: http://119.3.222.119:8000/oauth/check_token

mybatis:
  type-aliases-package: cn.zhengjunren.myblog.business.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
  page-size-zero: true
